services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    command: mongod --auth
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongodbdata:/data/db

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${CONFIG_MONGODB_ADMINUSERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${CONFIG_MONGODB_ADMINPASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${CONFIG_MONGODB_ADMINUSERNAME}:${CONFIG_MONGODB_ADMINPASSWORD}@mongo:27017/
  #     ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USERNAME}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWORD}

volumes:
  mongodbdata:
    driver: local
